name: CI-CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: bookstore
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.25.1
      
      - name: Debug
        run: echo "$DB_URL"

      - name: Run Migrations
        run: go run ./cmd/migrate/main.go up

      - name: Build
        run: go build -v ./cmd/api

      - name: Test
        run: go test -v -failfast -cover ./...
        # env:
        #   DB_HOST: localhost
        #   DB_PORT: 5432
        #   DB_USER: postgres
        #   DB_PASSWORD: postgres
        #   DB_NAME: bookstore
        #   SECRET_KEY: ${{ secrets.SECRET_KEY }}
